version: "3"

services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=dream
      - POSTGRES_DB=dream
      - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes:
      - ./docker/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # web:
  #   build: .
  #   ports:
  #     - "8080:8080"
  #   links:
  #     - postgres
  #   restart: always
  #   logging:
  #     driver: ${LOGGING_DRIVER:-json-file}
